#
server:
  port: 8080
spring:
  main:
    banner-mode=off:
  datasource:
    url: jdbc:postgresql://localhost:5433/cloud
    username: cloud
    password: cloud
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ##none, validate, update, create, create-drop
      ddl-auto: update
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true

    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO


